const fs = require('fs');
const path = require('path');

const docsDir = path.resolve(__dirname, '../docs');
const categories = [
  { folder: '', name: 'Overview', icon: 'BookOpen' },
  { folder: 'setup', name: 'Setup & Installation', icon: 'Wrench' },
  { folder: 'backend', name: 'Backend Architecture', icon: 'Server' },
  { folder: 'frontend', name: 'Frontend Architecture', icon: 'Layout' },
  { folder: 'database', name: 'Database & Schema', icon: 'Database' },
  { folder: 'ingestion', name: 'Log Ingestion', icon: 'ArrowDownToLine' },
  { folder: 'deployment', name: 'Cloud Deployment', icon: 'Cloud' },
  { folder: 'testing', name: 'Testing & Quality', icon: 'CheckCircle' },
  { folder: 'security', name: 'Security & Hardening', icon: 'ShieldCheck' },
  { folder: 'operations', name: 'Operations & Runbooks', icon: 'Terminal' },
  { folder: 'diagrams', name: 'Architecture Diagrams', icon: 'Workflow' },
  { folder: 'reference', name: 'Reference & Standards', icon: 'FileText' }
];

const docs = [];

for (const cat of categories) {
  const targetDir = cat.folder ? path.join(docsDir, cat.folder) : docsDir;
  if (!fs.existsSync(targetDir)) continue;
  
  const entries = fs.readdirSync(targetDir, { withFileTypes: true });
  const files = entries
    .filter(e => e.isFile() && e.name.endsWith('.md'))
    .map(e => e.name)
    .sort();

  for (const f of files) {
    const relPath = cat.folder ? `${cat.folder}/${f}` : f;
    const fullPath = path.join(targetDir, f);
    const content = fs.readFileSync(fullPath, 'utf8');
    
    // Extract title from first # heading or filename
    const h1Match = content.match(/^#\s+(.+)$/m);
    let title = h1Match ? h1Match[1].trim() : f.replace('.md', '').replace(/_/g, ' ');
    // Clean up title if it starts with "SentinelX — "
    title = title.replace(/^SentinelX\s*[—–-]\s*/, '').trim();
    if (!title) title = f.replace('.md', '').replace(/_/g, ' ');
    
    // Extract description from first non-heading, non-table, non-code line
    const lines = content.split('\n');
    let desc = '';
    for (const line of lines) {
      const trimmed = line.trim();
      if (
        trimmed &&
        !trimmed.startsWith('#') &&
        !trimmed.startsWith('|') &&
        !trimmed.startsWith('```') &&
        !trimmed.startsWith('![') &&
        !trimmed.startsWith('>') &&
        !trimmed.startsWith('-') &&
        !trimmed.startsWith('*')
      ) {
        desc = trimmed.replace(/[*_`]/g, '').slice(0, 160);
        if (trimmed.length > 160) desc += '...';
        break;
      }
    }

    docs.push({
      id: relPath.replace('.md', ''),
      path: relPath,
      category: cat.name,
      categoryFolder: cat.folder,
      icon: cat.icon,
      filename: f,
      title,
      description: desc || `Documentation for ${title}`,
      content
    });
  }
}

console.log(`Total documents compiled: ${docs.length}`);
const outputPath = path.resolve(__dirname, '../frontend/src/docsData.js');
fs.writeFileSync(
  outputPath,
  `// Auto-generated by scripts/build_docs_data.js - SentinelX Documentation Registry\nexport const docsData = ${JSON.stringify(docs, null, 2)};\nexport default docsData;\n`,
  'utf8'
);
console.log(`Successfully generated: ${outputPath}`);
